(** 
#Mechanism 6
    A, B: principal
    Kab, : symkey
    Na, Nb : nonce
    1, 2 : tag

    B -> A : Nb
    A -> B : {1, Na, Nb, B, Ka}_Kab
    B -> A : {2, Nb, Na, Kb}_Kbs
**)

set securityTypes = true.

include Logic.

(*---------------------------*)
(*  Declarations             *)
(*---------------------------*)

channel c.

senc enc,dec.

hash kdf.  (* kdf as a keyed hash function *)
name hk:message, Low. (* this key is actually secret, but we handle
                         the kdf with the usual Squirrel tactics, not by typing,
                         so we mark it as Low for the type system. *)

(* id(i): identity of (honest) agent i *)
abstract id : index -> message.

(* idD(i): identity of dishonest agent i *)
abstract idD : index -> message.


(* tags *)
abstract tag1: message. 
abstract tag2: message.
axiom[any] cst_diff1 : tag1 <> tag2 <: Real.z.
hint rewrite cst_diff1.


(*---------------------------*)
(* long-term shared keys *)
(* Kab(i, j): between id(i) and id(j) *)
name Kab : index * index -> message, 
  SK[enc, Cst tag1 * (High * (Low * (Cst id * High)))
        + Cst tag2 * (Low * (High * High))].

(* KHDab(i,j): between id(i) and idD(j) *)
name KHDab: index * index -> message, Low.

(* KHDab(i,j): between idD(i) and id(j) *)
name KDHab: index * index -> message, Low.


(*---------------------------*)
(* exchanged key material *)
(* Fa(i,j,k): generated by id(i) as Init in its k-th session w/ id(j) as Resp *)
name Fa : index * index * index -> message, High.

(* Fb(i,j,k): generated by id(j) as Resp in its k-th session w/ id(i) as Init *)
name Fb : index * index * index -> message, High.

(* FDa(i,j,k): generated by id(i) as Init in k-th session w/ idD(j) as Resp *)
name FDa : index * index * index -> message, Low.

(* FDb(i,j,k): generated by id(j) as Resp in k-th session w/ idD(i) as Init *)
name FDb : index * index * index -> message, Low.


(*---------------------------*)
(* nonces (random numbers) *)
(* Na(i,j,k): generated by id(i) as Init in its k-th session w/ id(j) as Resp *)
name Na: index * index * index -> message, High.

(* Nb(i,j,k): generated by id(j) as Resp in its k-th session w/ id(i) as Init *)
name Nb: index * index * index -> message, Low.

(* NDa(i,j,k): generated by id(i) as Init in k-th session w/ idD(j) as Resp *)
name NDa: index * index * index -> message, Low.

(* NDb(i,j,k): generated by id(j) as Resp in k-th session w/ idD(i) as Init *)
name NDb: index * index * index -> message, Low.


(*---------------------------*)
(*  Encryption randomness    *)
name Ra : index * index * index -> message, Rand.
name Rb : index * index * index -> message, Rand.

name RDa : index * index * index -> message, Low.
name RDb : index * index * index -> message, Low.


(*---------------------------*)
(* fresh key (artefact used to write lemmas) *)
name Kfresh: message, High.



(*---------------------------*)
(*  System                   *)
(*---------------------------*)

(* id(i) as Init in its k-th session with id(j) as Resp *)
process InitH(i,j,k:index) =
  IH1 : in(c,x); 
        out(c, enc(<tag1, <Na(i,j,k), <x, <id(j), Fa(i,j,k)>>>>,
                   Ra(i,j,k),
                   Kab(i,j)));
  IH2 : in(c,y);
        let mIH = dec(y,Kab(i,j)) in
        if mIH <> fail 
        && fst(mIH) = tag2
        && fst(snd(mIH)) = x
        && fst(snd(snd(mIH))) = Na(i,j,k)
        then
          let Nb_a = x in
          let Fb_a = snd(snd(snd(mIH))) in
          let Ka = kdf(<Fa(i,j,k), <Fb_a, <Na(i,j,k), Nb_a>>>, hk) in
          out(c, empty).

(* id(i) as Init in its k-th session with idD(j) as Resp *)
process InitD(i,j,k:index) =
  ID1 : in(c,x); 
        out(c, enc(<tag1, <NDa(i,j,k), <x, <idD(j), FDa(i,j,k)>>>>,
                   RDa(i,j,k),
                   KHDab(i,j)));
  ID2 : in(c,y);
        let mID = dec(y,KHDab(i,j)) in
        if mID <> fail 
        && fst(mID) = tag1
        && fst(snd(mID)) = x
        && fst(snd(snd(mID))) = NDa(i,j,k)
        then out(c, empty).

(* id(j) as Resp in its k-th session with id(i) as Init *)
process RespH(i,j,k:index)=
  RH1 : out(c, Nb(i,j,k));
  RH2 : in(c,y); 
        let mRH = dec(y,Kab(i,j)) in
        if mRH <> fail 
        && fst(mRH) = tag1
        && fst(snd(snd(mRH))) = Nb(i,j,k)
        && fst(snd(snd(snd(mRH)))) = id(j)
        then 
          let Na_b = fst(snd(mRH)) in
          let Fa_b = snd(snd(snd(snd(mRH)))) in
          let Kb = kdf(<Fa_b, <Fb(i,j,k), <Na_b, Nb(i,j,k)>>>, hk) in
          out(c, enc(<tag2, <Nb(i,j,k), <fst(snd(mRH)), Fb(i,j,k)>>>,
                     Rb(i,j,k),
                     Kab(i,j))).

(* id(j) as Resp in its k-th session with idD(i) as Init *)
process RespD(i,j,k:index)=
  RD1 : out(c, NDb(i,j,k));
  RD2 : in(c,y); 
        let mID = dec(y,KDHab(i,j)) in
        if mID <> fail 
        && fst(mID) = tag1
        && fst(snd(snd(mID))) = NDb(i,j,k)
        && fst(snd(snd(snd(mID)))) = id(j)
        then 
          out(c, enc(<tag2, <NDb(i,j,k), <fst(snd(mID)), FDb(i,j,k)>>>,
                     RDb(i,j,k), 
                     KDHab(i,j))).


system  !_i !_j !_k 
    (  InitH(i,j,k) 
     | RespH(i,j,k) 
     | InitD(i,j,k) 
     | RespD(i,j,k))
   | !_l (O: in(c, x); out(c, kdf(x,hk))).



(*---------------------------*)
(*  Lemmas                   *)
(*---------------------------*)

(* Secrecy of the key material from the point of view of Init *)
(* First, secrecy of Init's key material *)
lemma key_secrecy_init_partA (tau:timestamp) (i,j,k:index) :
  happens(tau) => 
  att(frame@tau) <> Fa(i,j,k).
Proof.
  intro *. 
  typing Meq. 
Qed.

(* Then secrecy of Resp's key material *)
lemma key_secrecy_init_partB (tau:timestamp) (i,j,k:index):
  IH2(i,j,k) <= tau => 
  att(frame@tau) <> if cond@IH2(i,j,k) then 
                      snd(snd(snd(dec(input@IH2(i,j,k),Kab(i,j)))))
                    else  
                      Kfresh.
Proof.
  intro *. 
  expandall.
  by typing Meq.
Qed.

(* Note the "else Kfresh" in the lemma above:
   we in fact prove secrecy only when cond@IH2 holds,
   and use a fresh value Kfresh (trivially secret) when it does not.
   We write the lemma with an "if then else" to make sure snd(…) is only
   typechecked when explicitly under cond@IH2.
   We could then write the following lemma, with an arguably more natural
   formulation: *)
lemma key_secrecy_init_partB_cond (tau:timestamp) (i,j,k:index):
  IH2(i,j,k) <= tau =>   
  cond@IH2(i,j,k) => 
  att(frame@tau) <> snd(snd(snd(dec(input@IH2(i,j,k),Kab(i,j))))).
Proof.
  intro _ _ _.
  have L := (key_secrecy_init_partB tau i j k _); [1:assumption].
  by rewrite if_true in L. 
Qed.
    
  
(*---------------------------*)
(* Secrecy of the key material from the point of view of Resp *)
(* First, secrecy of Resp's key material *)
lemma key_secrecy_resp_partB (tau:timestamp) (i,j,k:index):
   happens(tau) =>
   att(frame@tau) <> Fb(i,j,k).
Proof.
  intro *. 
  typing Meq.
Qed.

(* Then secrecy of Resp's key material *)
lemma key_secrecy_resp_partA (tau:timestamp) (i,j,k:index):
   happens(tau) =>
   tau >= RH2(i,j,k) => 
   att(frame@tau) <> if cond@RH2(i,j,k) then 
                       snd(snd(snd(snd(dec(input@RH2(i,j,k),Kab(i,j))))))
                     else
                       Kfresh.
Proof.
  intro *. 
  expandall.
  by typing Meq.
Qed.




(*---------------------------*)
(* Strong secrecy of the final key agreed upon *)

game Empty = {}. (* trick to prove equiv(frame@tau) when no diffs *)

(* from the point of view of Init *)
global lemma strong_secrecy_ka (tau:timestamp[const]) (i,j,k:index[const]):
   [IH2(i,j,k) <= tau] ->
   equiv(frame@tau, diff(Ka i j k@IH2(i, j, k), Kfresh)).
Proof.
  intro Hle.
  rewrite /Ka in 1.
  prf 1.
  + intro l HO Heq.
    rewrite /Fb_a /Nb_a in Heq.
    expandall.
    typing Heq.
  + fresh 1; [1:true].
    crypto Empty.
Qed.


(* from the point of view of Resp *)
global lemma strong_secrecy_kb (tau:timestamp[const]) (i,j,k:index[const]):
   [RH2(i,j,k) <= tau] ->
   equiv(frame@tau, diff(Kb i j k@RH2(i, j, k), Kfresh)).
Proof.
  intro Hle.
  rewrite /Kb in 1.
  prf 1.
  + intro l HO Heq.
    rewrite /Fa_b /Na_b in Heq.
    expandall.
    typing Heq.
  + fresh 1; [1:true].
    crypto Empty.
Qed.
