(** 
#Mechanism 6
    A, B: principal
    Kab, : symkey
    Na, Nb : nonce
    1, 2 : tag

    B -> A : Nb
    A -> B : {1, Na, Nb, B, Ka}_Kab
    B -> A : {2, Nb, Na, Kb}_Kbs
**)

set securityTypes = true.

include Logic.

channel c.

senc enc,dec.

(* id(i) identifier of (honest) agent i *)
abstract id : index -> message.

(* tag *)
abstract tag1:  message. 
abstract tag2: message. 
axiom[any] cst_diff1 : tag1 <> tag2 <: Real.z.
hint rewrite cst_diff1.

(* Kab(i) long-term key shared between id(i) and the server *)
name Kab : index * index -> message, SK[enc, Cst tag1 * (High * (Low * (Cst id * High)))
                                           + Cst tag2 * (Low * (High * High))].

(* Ka(i,j,k) part of the session key generated by Init played
 by  agent id(i) with agent id(j) at session k *)
name Ka : index * index * index -> message, High.
(* Kb(i,j,k) part of the session key generated by Resp played
 by  agent id(j) with agent id(i) at session k *)
name Kb : index * index * index -> message, High.

name Na: index * index * index -> message, High.
name Nb: index * index * index -> message, Low.
name Kfresh: message, High.

(* Randoms used in encryption *)
name Ra : index * index * index -> message, Rand.
name Rb : index * index * index -> message, Rand.

process Init(i,j,k:index)=
  I1 : in(c,x); out(c, enc(<tag1, <Na(i,j,k), <x, <id(j), Ka(i,j,k)>>>>,Ra(i,j,k),Kab(i,j)));
  I2:  in(c,y);
       let mI = dec(y,Kab(i,j)) in
       let kbI = snd(snd(snd(mI))) in
       if mI <> fail 
       && fst(mI) = tag2
       && fst(snd(mI)) = x
       && fst(snd(snd(mI))) = Na(i,j,k)
       then out(c, empty).

process Resp(i,j,k:index)=
  R1 : out(c, Nb(i,j,k));
  R2:  in(c,y); 
       let mR = dec(y,Kab(i,j)) in
       let kaR = snd(snd(snd(snd(mR)))) in
       if mR <> fail 
       && fst(mR) = tag1
       && fst(snd(snd(mR))) = Nb(i,j,k)
       && fst(snd(snd(snd(mR)))) = id(j)
       then out(c,enc(<tag2, < Nb(i,j,k), < fst(snd(mR)), Kb(i,j,k)>>>,Rb(i,j,k),Kab(i,j))).

system ( !_i !_j !_k ( Init(i,j,k) | Resp(i,j,k) )).

(* secrecy from the point of view of the initiator *)
lemma key_secrecy_init_partA: forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) => att(frame@tau) <> Ka(i,j,k).
Proof.
  intro *. 
  typing Meq. 
Qed.

lemma key_secrecy_init_partB : forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) =>  tau >= I2(i,j,k) => 
   att(frame@tau) <> if cond@I2(i,j,k) then kbI@I2(i,j,k) else Kfresh.
Proof.
  intro *. 
  expandall.
  by typing Meq.
Qed.

(* secrecy from the point of view of the responder *)
lemma key_secrecy_resp_partB : forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) =>  att(frame@tau) <> Kb(i,j,k).
Proof.
  intro *. 
  typing Meq.
Qed.

lemma key_secrecy_resp_partA : forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) =>  tau >= R2(i,j,k) => 
   att(frame@tau) <> if cond@R2(i,j,k) then kaR@R2(i,j,k) else Kfresh.
Proof.
  intro *. 
  expandall.
  by typing Meq.
Qed.
