(** 
#Needham-Schroeder (without the challenge-response mechanism) 
    A, B, S : principal
    Kas, Kbs, K : symkey
    Na: nonce

    A -> S : A, B, Na
    S -> {B, Na, K, {resp, K, A}_Kbs}_Kas
    A -> B : {resp, K, A}Kbs
**)

set securityTypes = true.

include Logic.

channel c.

senc enc,dec.

(* id(i) identifier of (honest) agent i *)
abstract id : index -> message.
(* idD(i) is the identifier of dishonest agent i *)
abstract idD: index -> message.
(* tag *)
abstract resp: message.
(* axioms for different constants *)
axiom[any] cst_id_idD : forall i j, id i <> idD j <: Real.z.
hint rewrite cst_id_idD.
axiom[any] cst_resp_id : forall i, id i <> resp <: Real.z.
hint rewrite cst_resp_id.
axiom[any] cst_resp_idD : forall i, idD i <> resp <: Real.z.
hint rewrite cst_resp_idD.

(* Ks(i) long-term key shared between id(i) and the server *)
name Ks : index -> message, SK[enc, Cst id * (Low * (High * Low)) + Cst resp * (High * Cst id)
                                  + Cst idD * (Low * (Low * Low)) + Cst resp * (Low * Cst idD)].

(* K(i,j,h) session key established by agent id(i) with agent id(j) at session k *)
name K : index * index * index -> message, High.
name Na: index * index * index -> message, Low.

name Kfresh: message, High.

(* KDs(i) long-term key shared between idD(i) and the server *)
name KDs: index -> message, Low.
name NDa: index * index * index -> message, Low.

(* KHD(i,j,k)/KDH(i,j,k) session key generated by the server for agent id(i) and idD(j) - resp. idD(i) and id(j) *)
name KHD: index * index * index -> message, Low.
name KDH: index * index * index -> message, Low.
 
(* Randoms used in encryption *)
name Ra : index * index * index -> message, Rand.
name Rb : index * index * index -> message, Rand.

name RHDa : index * index * index -> message, Rand.
name RHDb : index * index * index -> message, Low.

name RDHa : index * index * index -> message, Low.
name RDHb : index * index * index -> message, Rand.


process InitH(i,j,k:index)=
  IH1: out(c, <id(i),<id(j),Na(i,j,k)>>);
  IH2: in(c,x);  
       let mIH = dec(x,Ks(i)) in
       let kI = fst(snd(snd(mIH))) in
       if mIH <> fail && fst(mIH) = id(j) && fst(snd(mIH)) = Na(i,j,k)
       then out(c, snd(snd(snd(mIH)))). 

process InitD(i,j,k:index)=
  ID1: out(c, <id(i),<idD(j),NDa(i,j,k)>>);
  ID2: in(c,x);  
       let mID = dec(x,Ks(i)) in
       if mID <> fail && fst(mID) = idD(j) && fst(snd(mID)) = NDa(i,j,k)
       then out(c, snd(snd(snd(mID)))). 

process ServerHH(i,j,k:index)=
  SHH: in(c, x);
       if fst(x) = id(i) && snd(x) = id(j)
       then out(c, enc(<id(j), <snd(snd(x)), <K(i,j,k), 
                   enc(<resp, <K(i,j,k), id(i)>>, Rb(i,j,k), Ks(j))>>>, 
                   Ra(i,j,k), Ks(i))).

process ServerHD(i,j,k:index)=
  SHD: in(c, x);
       if fst(x) = id(i) && snd(x) = idD(j)
       then out(c, enc(<idD(j), <snd(snd(x)), <KHD(i,j,k), 
                   enc(<resp, <KHD(i,j,k), id(i)>>, RHDb(i,j,k), KDs(j))>>>, 
                   RHDa(i,j,k), Ks(i))).

process ServerDH(i,j,k:index)=
  SDH: in(c, x);
       if fst(x) = idD(i) && snd(x) = id(j)
       then out(c, enc(<id(j), <snd(snd(x)), <KDH(i,j,k), 
                   enc(<resp, <KDH(i,j,k), idD(i)>>, RDHb(i,j,k), Ks(j))>>>, 
                   RDHa(i,j,k), KDs(i))).

process RespH(i,j,k:index)=
  RH: in(c, x);
      let mRH = dec(x,Ks(j)) in
      let kR = fst(snd(mRH)) in
      if mRH <> fail && fst(mRH) = resp  && snd(snd(mRH)) = id(i) 
      then out(c,empty).

process RespD(i,j,k:index)=
  RD: in(c, x);
      let mRD = dec(x,Ks(j)) in
      if  mRD <> fail && fst(mRD) = resp && snd(snd(mRD)) = idD(i) 
      then out(c,empty).

system ( !_i !_j !_k (InitH(i,j,k) | ServerHH(i,j,k) | RespH(i,j,k)  | 
                      InitD(i,j,k) | ServerHD(i,j,k) | 
                                     ServerDH(i,j,k) | RespD(i,j,k)
)).
Proof.
  auto.
Qed.

(* secrecy from the point of view of the initiator *)
lemma key_secrecy_init: forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) => tau >= IH2(i,j,k) => 
   att(frame@tau) <> 
   if cond@IH2(i,j,k) then kI@IH2(i,j,k) else Kfresh.
Proof.
  intro *. 
  expandall.
  by typing Meq.
Qed.

(* secrecy from the point of view of the server *)
lemma key_secrecy_server: forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) =>  att(frame@tau) <> K(i,j,k).
Proof.
  intro *. 
  typing Meq.
Qed.

(* secrecy from the point of view of the responder *)
lemma key_secrecy_resp : forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) => tau >= RH(i,j,k) => 
   att(frame@tau) <> 
   if cond@RH(i,j,k) then kR@RH(i,j,k) else Kfresh.
Proof.
  intro *.
  expandall.
  by typing Meq.
Qed.

