(** 
#Mechanism 6 without tag 
    A, B: principal
    Kab, : symkey
    Na, Nb : nonce

    B -> A : Nb
    A -> B : {Na, Nb, B, Ka}_Kab
    B -> A : {Nb, Na, Kb}_Kbs
**)

set securityTypes = true.

include Logic.

channel c.

senc enc,dec.

(* id(i) identifier of (honest) agent i *)
abstract id : index -> message.

(* idD(i) identifier of dishonest agent i *)
abstract idD : index -> message.

(* Kab(i) long-term key shared between id(i) and the server *)
name Kab : index * index -> message, SK[enc, High * (Low * (Cst id * High))
                                           + Low * (High * High)].

name KHDab: index * index -> message, Low.
name KDHab: index * index -> message, Low.

(* Ka(i,j,k) part of the session key generated by Init played
 by  agent id(i) with agent id(j) at session k *)
name Ka : index * index * index -> message, High.
(* Kb(i,j,k) part of the session key generated by Resp played
 by  agent id(j) with agent id(i) at session k *)
name Kb : index * index * index -> message, High.

name Na: index * index * index -> message, High.
name Nb: index * index * index -> message, Low.
name Kfresh: message, High.

(* data generated and shared with dishonest agents *)
name KDa : index * index * index -> message, Low.
name KDb : index * index * index -> message, Low.

name NDa: index * index * index -> message, Low.
name NDb: index * index * index -> message, Low.

(* Randoms used in encryption *)
name Ra : index * index * index -> message, Rand.
name Rb : index * index * index -> message, Rand.

name RDa : index * index * index -> message, Low.
name RDb : index * index * index -> message, Low.

process InitH(i,j,k:index)=
  IH1 : in(c,x); out(c, enc(<Na(i,j,k), <x, <id(j), Ka(i,j,k)>>>,Ra(i,j,k),Kab(i,j)));
  IH2:  in(c,y);  
       if  dec(y,Kab(i,j)) <> fail 
        && fst(dec(y,Kab(i,j))) = x
        && fst(snd(dec(y,Kab(i,j)))) = Na(i,j,k)
       then out(c, empty).

process InitD(i,j,k:index)=
  ID1 : in(c,x); out(c, enc(<NDa(i,j,k), <x, <idD(j), KDa(i,j,k)>>>,RDa(i,j,k),KHDab(i,j)));
  ID2:  in(c,y);  
       if  dec(y,KHDab(i,j)) <> fail 
        && fst(dec(y,KHDab(i,j))) = x
        && fst(snd(dec(y,KHDab(i,j)))) = NDa(i,j,k)
       then out(c, empty).

process RespH(i,j,k:index)=
  RH1 : out(c, Nb(i,j,k));
  RH2:  in(c,y); 
       if   dec(y,Kab(i,j)) <> fail 
         && fst(snd(dec(y,Kab(i,j)))) = Nb(i,j,k)
         && fst(snd(snd(dec(y,Kab(i,j))))) = id(j)
       then out(c,enc(< Nb(i,j,k), < fst(snd(dec(y,Kab(i,j)))), Kb(i,j,k)>>,Rb(i,j,k),Kab(i,j))).

process RespD(i,j,k:index)=
  RD1 : out(c, NDb(i,j,k));
  RD2:  in(c,y); 
       if   dec(y,KDHab(i,j)) <> fail 
         && fst(snd(dec(y,KDHab(i,j)))) = NDb(i,j,k)
         && fst(snd(snd(dec(y,KDHab(i,j))))) = id(j)
       then out(c,enc(< NDb(i,j,k), < fst(snd(dec(y,KDHab(i,j)))), KDb(i,j,k)>>,RDb(i,j,k),KDHab(i,j))).

system ( !_i !_j !_k ( InitH(i,j,k) | RespH(i,j,k) | InitD(i,j,k) | RespD(i,j,k) )).

(* secrecy from the point of view of the initiator *)
lemma key_secrecy_init_partA: forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) => att(frame@tau) <> Ka(i,j,k).
Proof.
  intro *. 
  checkfail typing Meq exn Failure.
Abort.


lemma key_secrecy_init_partB : forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) =>  tau >= IH2(i,j,k) => 
   att(frame@tau) <> if cond@IH2(i,j,k) then snd(snd(snd(dec(input@IH2(i,j,k),Kab(i,j))))) else Kfresh.
Proof.
  intro *. 
  expand cond.
  checkfail typing Meq exn Failure.
Abort.

(* secrecy from the point of view of the responder *)
lemma key_secrecy_resp_partB : forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) =>  att(frame@tau) <> Kb(i,j,k).
Proof.
  intro *.
  checkfail typing Meq exn Failure.
Abort.

lemma key_secrecy_resp_partA : forall (tau:timestamp), forall (i,j,k:index),
   happens(tau) =>  tau >= RH2(i,j,k) => 
   att(frame@tau) <> if cond@RH2(i,j,k) then snd(snd(snd(snd(dec(input@RH2(i,j,k),Kab(i,j)))))) else Kfresh.
Proof.
  intro *. 
  expand cond.
  checkfail typing Meq exn Failure.
Abort.
